### ISSUE TITLE
futhark-flycheck.el gives error when entering futhark-mode

### ISSUE THREAD

**Issue by badly-drawn-wizards** [diku-dk/futhark-mode#4]
I'm getting an error in futhark-flycheck.el that `source-inplace` is undefined. I'm running version 0.2, with Doom Emacs using nix-doom-emacs.

`doom/version` gives
```
Doom v2.0.9 (n/a)
Emacs v26.3
```

**Comment by athas** [comment]
That's odd.  That code only runs when flycheck is available, and I wasn't aware that `source-inplace` is not always available.

**Comment by athas** [comment]
The flycheck stuff is gone now.  We're now all in on LSP.
